---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: amazon fsx for ontap, volumes, aws, access key, secret key 
summary: ONTAP용 Amazon FSx는 고객이 NetApp의 ONTAP 스토리지 운영 체제가 제공하는 파일 시스템을 시작하고 실행할 수 있도록 하는 완전 관리형 서비스입니다. ONTAP용 FSX는 NetApp 고객이 현재 사내에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 기본 AWS 서비스의 단순성, 민첩성, 보안 및 확장성으로 제공합니다. 
---
= ONTAP용 Amazon FSx에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["ONTAP용 Amazon FSx"^] 는 고객이 NetApp의 ONTAP 스토리지 운영 체제가 제공하는 파일 시스템을 실행하고 실행할 수 있도록 하는 완전 관리형 서비스입니다. ONTAP용 FSX는 NetApp 고객이 사내에서 사용하는 것과 동일한 기능, 성능 및 관리 기능을 기본 AWS 서비스의 단순성, 민첩성, 보안 및 확장성으로 제공합니다.



== 피처

* 스토리지 디바이스, 소프트웨어 또는 백업을 구성하거나 관리할 필요가 없습니다.
* CIFS, NFSv3, NFSv4.x 및 SMB v2.0-v3.1.1 프로토콜 지원
* 자주 액세스하지 않는(IA) 스토리지 계층을 사용하여 저렴한 비용으로 사실상 제한 없는 데이터 스토리지 용량을 확보할 수 있습니다.
* Oracle RAC를 포함하여 지연 시간에 민감한 애플리케이션에서 실행되도록 인증받았습니다.
* 번들 및 용량제 가격 선택 가능




== 추가 기능은 Cloud Manager에서 제공됩니다

* AWS 및 Cloud Manager의 커넥터를 사용하여 볼륨을 생성 및 관리하고, 데이터를 복제하고, ONTAP용 FSx를 데이터 센스 및 Cloud Sync와 같은 NetApp 클라우드 서비스와 통합할 수 있습니다.
* 클라우드 데이터 센스는 인공 지능(AI) 기반 기술을 사용하여 데이터 컨텍스트를 이해하고 FSx for ONTAP 계정에 상주하는 중요한 데이터를 식별하는 데 도움을 줄 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["자세한 정보"^].
* NetApp Cloud Sync를 사용하면 클라우드 또는 사내 타겟으로 데이터 마이그레이션을 자동화할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["자세한 정보"^]




== 비용

ONTAP용 FSx 계정은 Cloud Manager가 아니라 AWS에서 유지 관리됩니다. https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["ONTAP용 Amazon FSx 시작 가이드"^]

AWS에서 커넥터를 사용하는 것과 Cloud Sync 및 데이터 센스와 같은 선택적 데이터 서비스를 사용하는 것과 관련된 추가 비용이 있습니다.



== 지원 지역

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 아마존 지역을 봅니다."^]



== 도움말 보기

ONTAP용 Amazon FSx는 AWS 최초의 솔루션입니다. 이 서비스를 사용하는 AWS FSx 파일 시스템, 인프라 또는 AWS 솔루션과 관련된 질문이나 기술 지원 문제가 있는 경우 AWS 콘솔의 Support Center를 사용하여 AWS에 지원 케이스를 접수하십시오. “FSx for ONTAP” 서비스와 적절한 범주를 선택합니다. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공합니다.

Cloud Manager 또는 Cloud Manager 마이크로 서비스와 관련된 일반적인 질문은 인라인 Cloud Manager 채팅으로 시작할 수 있습니다.

Cloud Manager 또는 내의 마이크로 서비스와 관련된 기술 지원 문제의 경우 Cloud Manager 계정 레벨 일련 번호를 사용하여 NetApp 지원 티켓을 열 수 있습니다. 지원을 활성화하려면 Cloud Manager 일련 번호를 등록해야 합니다.



== 제한 사항

* Cloud Manager는 온프레미스 또는 Cloud Volumes ONTAP에서 ONTAP용 FSx로 데이터를 복제할 수 있습니다.
* 이때 ONTAP CLI, ONTAP API 또는 Cloud Manager API를 사용하여 iSCSI 볼륨을 생성할 수 있습니다.
* 현재 ONTAP용 FSx의 SnapMirror 복제는 CLI를 사용하여 지원됩니다.

